x = input("Digite algo:")
print("{} é {}".format(x, type(x)))
print("{} só tem espaços ? {}".format(x, x.isspace()))
print("{} é número ? {}".format(x, x.isnumeric()))
print("{} é alfabético ? {}".format(x, x.isalpha()))
print("{} é alfanumérico ? {}".format(x, x.isalnum()))
print("{} está em maiúsculas ? {}".format(x, x.isupper()))
print("{} está em minúsculas ? {}".format(x, x.islower()))
print("{} está capitalizada ? {}".format(x, x.istitle()))